/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LPAREN = 4;
  /** RegularExpression Id. */
  int RPAREN = 5;
  /** RegularExpression Id. */
  int MOVE = 6;
  /** RegularExpression Id. */
  int PUT = 7;
  /** RegularExpression Id. */
  int PICK = 8;
  /** RegularExpression Id. */
  int TURN = 9;
  /** RegularExpression Id. */
  int FACE = 10;
  /** RegularExpression Id. */
  int MOVE_DIR = 11;
  /** RegularExpression Id. */
  int RUN_DIRS = 12;
  /** RegularExpression Id. */
  int MOVE_FACE = 13;
  /** RegularExpression Id. */
  int SK = 14;
  /** RegularExpression Id. */
  int BALLOONS = 15;
  /** RegularExpression Id. */
  int CHIPS = 16;
  /** RegularExpression Id. */
  int NUMERO = 17;
  /** RegularExpression Id. */
  int DIGIT = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"(\"",
    "\")\"",
    "\"move\"",
    "\"put\"",
    "\"pick\"",
    "\"turn\"",
    "\"face\"",
    "\"move_dir\"",
    "\"run_dirs\"",
    "\"move_face\"",
    "\"skip\"",
    "\":balloons\"",
    "\":chips\"",
    "<NUMERO>",
    "<DIGIT>",
    "\"\\n\"",
  };

}
