/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MOVE = 4;
  /** RegularExpression Id. */
  int TURN = 5;
  /** RegularExpression Id. */
  int T_PONER = 6;
  /** RegularExpression Id. */
  int T_RECOGER = 7;
  /** RegularExpression Id. */
  int T_POP = 8;
  /** RegularExpression Id. */
  int T_BALLOONS = 9;
  /** RegularExpression Id. */
  int T_CHIPS = 10;
  /** RegularExpression Id. */
  int NUMERO = 11;
  /** RegularExpression Id. */
  int DIGIT = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"move\"",
    "\"turn\"",
    "\"Put\"",
    "\"Pick\"",
    "\"Pop\"",
    "\"BALLOONS\"",
    "\"CHIPS\"",
    "<NUMERO>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"\\n\"",
    "\",\"",
  };

}
